### PR TITLE
Show dummy.html and Click to Load page instead of Loading page on view (Like TGS) + Keep/Show Tab Backups

### PR DESCRIPTION
**Pull request by Niush**
- When discarding tab, show dummy.html and click to load page instead of loading page on view. (#169)
- The dummy page will be then discarded completely by `chrome.tabs.discard` when active tab changes.
- While discarding, tab will not switch to next (otab), Because we load dummy.html instead over itself.
*Similar to, what The Great Suspender does. The original page url, title, favicon is shown in the dummy page. (via hash parameter)*
---
- To switch back to reloading page on View, An option is added in the settings page. (Defaults to click/reload)
- Internal Pages, that got discarded will load properly.
- Keep 5 latest tab backups, before every tab discard only.

demo

### CODE REVIEW

**Comment by markmandel** [comment]
Just wanted to swing by and say thank you for doing this work :+1: it's the major feature I've been looking for in replacing TGS :cartwheeling:

**Comment by rhclayto** [comment]
+1. Has anybody with merge rights looked at this PR?

**Comment by markmandel** [comment]
I just loaded this PR as an unpacked extension - will let you know if I run into any issues, but so far so good 👍

I am wondering if we should be changing the default behaviour to suspend to the dummy page - maybe it should be opt in? At least that way it's not a change in behaviour if/when the PR gets merged and released.

**Comment by Niush** [comment]
@markmandel Yes, I agree. I have now made the **release-on-view** option default to true. ([f03c5fe](https://github.com/rNeomy/auto-tab-discard/commit/f03c5fe89d4946dda6d32be89f0bcb693643d133#diff-9a84c5b02676e7657d8e8586ec2278f02552393c5186417973dc98fdbf8d086bR65))
Now, To enable click to load option like TGS we have to disable this settings from options page.

image

**Comment by markmandel** [comment]
@rNeomy is there anything specific that is blocking this PR from being merged? (Are the conflicts an issue?)

I'd really love to be running the official release, rather than loading from this PR's source.

**Comment by rNeomy** [comment]
@markmandel Having a local page causes a few issues. That's the reason why I am reluctant on having this feature:

1. What if the user uninstalled the extension. All locally discarded tabs are going to be gone. For instance, see https://github.com/greatsuspender/thegreatsuspender/issues/1313
2. Restoring the original page from the local one does not keep the tab's data such as scroll position, and form's data. For instance see https://github.com/greatsuspender/thegreatsuspender/search?q=scroll&type=issues
3. We need to keep track of all locally discarded tabs on a restart, which is a mess (tab index of each window).
4. We need to be compatible with the new tab grouping feature on Chrome when restoring tabs on a restart. The same goes for container tabs on Firefox.
5. It gets more complex if the user has multiple devices with synced tabs.
6. Dealing with incognito tabs. For instance see https://github.com/greatsuspender/thegreatsuspender/issues/1204

**Comment by Niush** [comment]
**For anyone wondering in my fork, feature number,**
1. 😢 N/A (But, sometimes chrome does not clear the tabs although the tab URL will not be the original one)
2. 😢 N/A (Unable to restore scroll or form. Hackly possible but would be an overkill)
3. 😃 Has been implemented to auto discard pages on browser/window restart.
4. 😃 Discarding Tab groups works in Chrome and Vivaldi properly. (Firefox not tested)
5. 😢 N/A (NO WAY syncing original url, can be implemented with this dummy page technique)
6. 😃 Can be fixed as required by using "[incognito](https://developer.chrome.com/docs/extensions/mv2/manifest/incognito/)" manifest key (should work by default).

I use Vivaldi as my main browser. It has built-in way to hibernate tabs which works similar to this extension and reloads page on view. I forked this extension so that it shows dummy page (like TGS) instead of reloading on view. Anyone can use my fork by loading it as unpacked extension.

Definitely, 1, 2, 5 are major problems that **cannot** be solved with dummy page technique.

**Comment by markmandel** [comment]
As a current user of this fork, I'll respond to 1,2 and 5, as it seems like 3 (I've had crashes multiple times, and this works!), 4 and 6 are covered:

1. I feel like that's on me as a user to not shoot myself in the foot. Also the URL is encoded in the dummy page, so if I _really_ need it, then I can get it. This is a documentation issue.
2. This is the tradeoff I get to choose as a use for opting in to this solution. So really, this seems to me to be a documentation issue.
5. Again, user choice. If I choose to use the dummy page option, then i can't sync. That's the tradeoff I choose to make as a user. We could document this as well.

This is also why I suggested above that the feature should specifically be _opt in_ and not break existing behaviour.

If you are concerned with breaking things (which I 100% get) -- maybe mark it as an experimental feature, and see what issues shake out after real usage?

**Comment by rNeomy** [comment]
I added a new branch with custom plugin support. The idea is to have all the code related to a plugin in its own directory and be able to enable and disable each plugin from the background script.
https://github.com/rNeomy/auto-tab-discard/tree/dummy-page

In this branch, there is a sample plugin (`/plugins/dummy/`) which when gets activated from the options page, the extension replaces the current page with a dummy alternative. By navigating to the dummy page instead of updating the tab's URL, the original page keeps its original data (fixes the second issue).

If we could somehow navigate to a local page (`data:text/html;base64,...`) instead of the current internal page (`/plugins/dummy/page.html`), then there would be no need for writing the custom session restoring since these pages are not going to be dependent to this extension. This is going to fix all the major concerns the dummy page has.

Let's try to find a way to navigate to a local page before importing @Niush work to the new plug-in system.

**Comment by lucknaumann** [comment]
@rNeomy I would prefer the local page vs the dummy page. I used an extension many years ago that used dummy pages and constantly lost my pages! Even using a session manager did no good as it, too, saved the dummy pages. Needless to say, I stopped using that extension.

**Comment by BraunLukas** [comment]
how can i enable this behaviour? 
unfortunately its disabled on firefox and brave

**Comment by rNeomy** [comment]
@BraunLukas this plug-in is not ready. As far as I know nobody is working on it at the moment.

**Pull request closed without merging**
